<a href="https://colab.research.google.com/github/Pradnyanand09/Pytorch/blob/main/Lec1_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [ ]:
if torch.cuda.is_available():
  print("GPU is availabel")
else:
  print("GPU is not availabel")

GPU is not availabel


## Creating a Tensor

In [ ]:
torch.empty(2,3)

tensor([[-1.9567e+24,  4.3512e-41,  6.9131e-34],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00]])

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,2)

tensor([[0.1811, 0.0707],
        [0.3301, 0.4384]])

Use of seed

In [ ]:
#seed
torch.manual_seed(100)
torch.rand(2,2)

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

Custom Tensor


In [ ]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#arange
print("using arange->" ,torch.arange(0,10))
print()

#linspace
print("using linspace->" ,torch.linspace(0,10,steps=10)) #10 evenly spcaed values
print()

#using eye
print("using eye ->" ,torch.eye(5))  #identity matrix
print()

print("using full ->" ,torch.full((3,3),5))

using arange-> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

using linspace-> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


#Tesnor shape

In [ ]:
x=torch.tensor([[2,3,4],[1,2,3]])
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x) #same shape values are diff

tensor([[    133366918622704,     133366918622704,                   0],
        [                  0,                   0, 7310593858020254331]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

# Tensor Data Types

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
print(x)
x.to(torch.float32) #x was interger and converted to float


tensor([[2, 3, 4],
        [1, 2, 3]])


tensor([[2., 3., 4.],
        [1., 2., 3.]])

# Mathematical operation